name: sdi-blend-project-3
services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: sdi-blend-project-3-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data

  frontend:
    build: ./ui
    ports:
      - '3000:3000'
    depends_on:
      - server

volumes:
  db:
